import * as core from "@qretools/core";
import * as editor from "@qretools/core/editor";
import * as node from "@qretools/core/node";
import { describe, expect, it } from "vitest";

/** The public surface, so any change to it shows up in review. Here, beside the Node entry, because it imports it. */
describe("the entry points", () => {
	it("export these values", () => {
		expect({
			core: Object.keys(core).sort(),
			editor: Object.keys(editor).sort(),
			node: Object.keys(node).sort(),
		}).toMatchInlineSnapshot(`
			{
			  "core": [
			    "AGENCY_PATTERN",
			    "EMPTY_ENV",
			    "FIELD_OF",
			    "FILL_TYPES",
			    "FOLDERS",
			    "FOLDER_PATTERN",
			    "FOLDER_RULE_TEXT",
			    "NAME_PATTERN",
			    "NAME_RULE_TEXT",
			    "PROJECT",
			    "REQUIRED_ROOTS",
			    "ROOT",
			    "SCHEME_KINDS",
			    "SCHEME_LABELS",
			    "SCHEME_NAME",
			    "SCHEME_SINGULAR",
			    "SHAPE",
			    "UNDECLARED_AGENCY",
			    "UNNAMED",
			    "UNVERSIONED",
			    "absentRoot",
			    "bankEnv",
			    "bankFindings",
			    "bankLocation",
			    "bankOf",
			    "codeSpans",
			    "codebookView",
			    "collisions",
			    "compact",
			    "definedVariables",
			    "documentOf",
			    "elaborate",
			    "elaborateItems",
			    "err",
			    "evaluate",
			    "evaluateScheme",
			    "exportRefusal",
			    "fileFindings",
			    "importsOf",
			    "inDocumentOrder",
			    "inScope",
			    "indexOf",
			    "instrumentOf",
			    "isRoot",
			    "kindAt",
			    "labelOf",
			    "lint",
			    "makeValidator",
			    "ok",
			    "optionVariable",
			    "othersOf",
			    "parseBankFile",
			    "parseScale",
			    "parseSurface",
			    "piecesOf",
			    "placeholders",
			    "plainText",
			    "projectOf",
			    "refusalReason",
			    "respondentView",
			    "saveableName",
			    "schemeEnv",
			    "schemePath",
			    "status",
			    "textOf",
			    "toFillIn",
			    "usedBy",
			  ],
			  "editor": [
			    "addSpace",
			    "applyEdits",
			    "bankFileJsonSchema",
			    "inspect",
			    "labelledJsonSchema",
			    "labelledSource",
			    "labelsJsonSchema",
			    "locate",
			    "marksOf",
			    "mentionAt",
			    "nameFrom",
			    "pathAt",
			    "placeAt",
			    "questionJsonSchema",
			    "quoteCode",
			    "rangesOf",
			    "renameEdits",
			    "spaceBefore",
			    "textEntryJsonSchema",
			    "textEntrySource",
			  ],
			  "node": [
			    "main",
			    "readBank",
			  ],
			}
		`);
	});
});
